
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.UIManager UIManager;

	private global::Gtk.Action File;

	private global::Gtk.Action Open;

	private global::Gtk.Action Save;

	private global::Gtk.Action Close;

	private global::Gtk.Action Help;

	private global::Gtk.Action Info;

	private global::Gtk.Action AboutA;

	private global::Gtk.VBox vbox1;

	private global::Gtk.MenuBar menubar1;

	private global::Gtk.HBox hbox1;

	private global::Gtk.Entry MainEntry;

	private global::Gtk.Button BtnAddRow;

	private global::Gtk.Button BtnDelRow;

	private global::Gtk.Button BtnAddCol;

	private global::Gtk.Button BtnDelCol;

	private global::Gtk.ScrolledWindow scrolledwindow;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.UIManager = new global::Gtk.UIManager();
		global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup("Default");
		this.File = new global::Gtk.Action("File", global::Mono.Unix.Catalog.GetString("_Файл"), null, null);
		this.File.ShortLabel = global::Mono.Unix.Catalog.GetString("_Файл");
		w1.Add(this.File, "<Alt><Mod2>f");
		this.Open = new global::Gtk.Action("Open", global::Mono.Unix.Catalog.GetString("_Відкрити"), null, null);
		this.Open.ShortLabel = global::Mono.Unix.Catalog.GetString("_Відкрити");
		w1.Add(this.Open, "<Primary><Mod2>o");
		this.Save = new global::Gtk.Action("Save", global::Mono.Unix.Catalog.GetString("З_берегти"), null, null);
		this.Save.ShortLabel = global::Mono.Unix.Catalog.GetString("З_берегти");
		w1.Add(this.Save, "<Primary><Mod2>s");
		this.Close = new global::Gtk.Action("Close", global::Mono.Unix.Catalog.GetString("З_акрити"), null, null);
		this.Close.ShortLabel = global::Mono.Unix.Catalog.GetString("З_акрити");
		w1.Add(this.Close, "<Primary><Mod2>l");
		this.Help = new global::Gtk.Action("Help", global::Mono.Unix.Catalog.GetString("_Допомога"), null, null);
		this.Help.ShortLabel = global::Mono.Unix.Catalog.GetString("_Допомога");
		w1.Add(this.Help, null);
		this.Info = new global::Gtk.Action("Info", global::Mono.Unix.Catalog.GetString("_Довідка"), null, null);
		this.Info.ShortLabel = global::Mono.Unix.Catalog.GetString("_Довідка");
		w1.Add(this.Info, "<Primary><Mod2>i");
		this.AboutA = new global::Gtk.Action("AboutA", global::Mono.Unix.Catalog.GetString("Про автора"), null, null);
		this.AboutA.ShortLabel = global::Mono.Unix.Catalog.GetString("Про автора");
		w1.Add(this.AboutA, null);
		this.UIManager.InsertActionGroup(w1, 0);
		this.AddAccelGroup(this.UIManager.AccelGroup);
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.UIManager.AddUiFromString(@"<ui><menubar name='menubar1'><menu name='File' action='File'><menuitem name='Open' action='Open'/><menuitem name='Save' action='Save'/><menuitem name='Close' action='Close'/></menu><menu name='Help' action='Help'><menuitem name='Info' action='Info'/><menuitem name='AboutA' action='AboutA'/></menu></menubar></ui>");
		this.menubar1 = ((global::Gtk.MenuBar)(this.UIManager.GetWidget("/menubar1")));
		this.menubar1.Name = "menubar1";
		this.vbox1.Add(this.menubar1);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.menubar1]));
		w2.Position = 0;
		w2.Expand = false;
		w2.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox1 = new global::Gtk.HBox();
		this.hbox1.Name = "hbox1";
		this.hbox1.Spacing = 6;
		// Container child hbox1.Gtk.Box+BoxChild
		this.MainEntry = new global::Gtk.Entry();
		this.MainEntry.CanFocus = true;
		this.MainEntry.Name = "MainEntry";
		this.MainEntry.Text = global::Mono.Unix.Catalog.GetString("Привіт!");
		this.MainEntry.IsEditable = false;
		this.MainEntry.InvisibleChar = '●';
		this.hbox1.Add(this.MainEntry);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.MainEntry]));
		w3.Position = 0;
		// Container child hbox1.Gtk.Box+BoxChild
		this.BtnAddRow = new global::Gtk.Button();
		this.BtnAddRow.CanFocus = true;
		this.BtnAddRow.Name = "BtnAddRow";
		this.BtnAddRow.UseUnderline = true;
		this.BtnAddRow.Label = global::Mono.Unix.Catalog.GetString("Додати рядок");
		this.hbox1.Add(this.BtnAddRow);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.BtnAddRow]));
		w4.Position = 1;
		w4.Expand = false;
		w4.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.BtnDelRow = new global::Gtk.Button();
		this.BtnDelRow.CanFocus = true;
		this.BtnDelRow.Name = "BtnDelRow";
		this.BtnDelRow.UseUnderline = true;
		this.BtnDelRow.Label = global::Mono.Unix.Catalog.GetString("Видалити рядок");
		this.hbox1.Add(this.BtnDelRow);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.BtnDelRow]));
		w5.Position = 2;
		w5.Expand = false;
		w5.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.BtnAddCol = new global::Gtk.Button();
		this.BtnAddCol.CanFocus = true;
		this.BtnAddCol.Name = "BtnAddCol";
		this.BtnAddCol.UseUnderline = true;
		this.BtnAddCol.Label = global::Mono.Unix.Catalog.GetString("Додати стовпчик");
		this.hbox1.Add(this.BtnAddCol);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.BtnAddCol]));
		w6.Position = 3;
		w6.Expand = false;
		w6.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.BtnDelCol = new global::Gtk.Button();
		this.BtnDelCol.CanFocus = true;
		this.BtnDelCol.Name = "BtnDelCol";
		this.BtnDelCol.UseUnderline = true;
		this.BtnDelCol.Label = global::Mono.Unix.Catalog.GetString("Видалити стовпчик");
		this.hbox1.Add(this.BtnDelCol);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.BtnDelCol]));
		w7.Position = 4;
		w7.Expand = false;
		w7.Fill = false;
		this.vbox1.Add(this.hbox1);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox1]));
		w8.Position = 1;
		w8.Expand = false;
		w8.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.scrolledwindow = new global::Gtk.ScrolledWindow();
		this.scrolledwindow.CanFocus = true;
		this.scrolledwindow.Name = "scrolledwindow";
		this.scrolledwindow.ShadowType = ((global::Gtk.ShadowType)(1));
		this.vbox1.Add(this.scrolledwindow);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.scrolledwindow]));
		w9.Position = 2;
		this.Add(this.vbox1);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 732;
		this.DefaultHeight = 300;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
		this.Open.Activated += new global::System.EventHandler(this.OpenActivated);
		this.Save.Activated += new global::System.EventHandler(this.SaveActivated);
		this.Close.Activated += new global::System.EventHandler(this.CloseActivated);
		this.Info.Activated += new global::System.EventHandler(this.InfoActivated);
		this.AboutA.Activated += new global::System.EventHandler(this.AboutA_Activated);
		this.BtnAddRow.Clicked += new global::System.EventHandler(this.BtnAddRowClicked);
		this.BtnDelRow.Clicked += new global::System.EventHandler(this.BtnDelRowClicked);
		this.BtnAddCol.Clicked += new global::System.EventHandler(this.BtnAddColClicked);
		this.BtnDelCol.Clicked += new global::System.EventHandler(this.BtnDelColClicked);
	}
}
